- id: doi:10.48550/arXiv.2405.14014
  title: 'RadarOcc: Robust 3D Occupancy Prediction with 4D Imaging Radar'
  authors:
  - Fangqiang Ding
  - Xiangyu Wen
  - Yunzhou Zhu
  - Yiming Li
  - Chris Xiaoxuan Lu
  date: '2024-05-22'
  publisher: NeurIPS
  image: images/works/radarocc.png