- id: doi:10.48550/arXiv.2405.14014
  title: 'RadarOcc: Robust 3D Occupancy Prediction with 4D Imaging Radar'
  authors:
  - Fangqiang Ding
  - Xiangyu Wen
  - Yunzhou Zhu
  - Yiming Li
  - Chris Xiaoxuan Lu
  date: '2024-05-22'
  publisher: NeurIPS
  image: images/works/radarocc.png

- id: IROS2025
  title: 'InverTwin: Solving Inverse Problems via Differentiable Radio Frequency Digital Twin'
  authors:
  - Chris Xiaoxuan Lu
  publisher: IEEE/RSJ International Conference on Intelligent Robots and Systems
  date: '2025'

- id: IROS2025
  title: 'ABC'
  authors:
  - Fangqiang Ding
  publisher: IEEE/RSJ International Conference on Intelligent Robots and Systems
  date: '2025'