- id: doi:10.48550/arXiv.2405.14014
  title: 'RadarOcc: Robust 3D Occupancy Prediction with 4D Imaging Radar'
  authors:
  - Fangqiang Ding
  - Xiangyu Wen
  - Yunzhou Zhu
  - Yiming Li
  - Chris Xiaoxuan Lu
  date: '2024-05-22'
  publisher: NeurIPS
  image: images/works/radarocc.png

- id: ding2025thermohands
  title: 'Thermohands: A benchmark for 3d hand pose estimation from egocentric thermal images'
  authors:
  - Fangqiang Ding
  - Yunzhou Zhu
  - Xiangyu Wen
  - Gaowen Liu
  - Chris Xiaoxuan Lu
  publisher: Proceedings of the 23rd ACM Conference on Embedded Networked Sensor Systems
  date: '2025'
  type: paper-conference